server.use-forward-headers=true
server.forward-headers-strategy=framework
spring.couchbase.bootstrap-hosts=localhost
spring.couchbase.bucket.name=travel-sample
spring.couchbase.bucket.user=Administrator
spring.couchbase.bucket.password=Couchbase@123
spring.couchbase.scope.name=inventory
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=couch2mongo
#spring.data.mongodb.uri=dummy
#spring.data.mongodb.database=dummy

#spring.profiles.active=couchbase
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
#org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

spring.profiles.active=mongodb
