server.use-forward-headers=true
server.forward-headers-strategy=framework
spring.couchbase.bootstrap-hosts=localhost
spring.couchbase.bucket.name=travel-sample
spring.couchbase.bucket.user=Administrator
spring.couchbase.bucket.password=Couchbase@123
spring.couchbase.scope.name=inventory
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=couch2mongo

# possible value for READ_FROM_DATABASE are mongodb or couchbase
READ_FROM_DATABASE=mongodb
# possible value for WRITE_TO_DATABASE are mongodb or couchbase or both
WRITE_TO_DATABASE=both

#spring.profiles.active=couchbase
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
#org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

#spring.profiles.active=mongodb
